title: CS 210 Project
description: A project I did for the CS 210 course at Sabanci University where I analyzed performance of my videos on Youtube Shorts and Instagram Reels.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
